name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Video
        run: curl "https://pixeldrain.dev/api/file/xqpvkdLu?download" -o video.mp4

      - name: Video Uplaoder
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run:
          curl -T "video.mp4" -u :${API_KEY} https://pixeldrain.com/api/file/videooo.mp4